name = "gysubway-github-io"
main = "server.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"] # 必须要有这个，不然 Supabase 依赖会崩

[observability]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

[observability.traces]
enabled = true
head_sampling_rate = 1
persist = true

[observability.issue_detection]
enabled = true
